// Re-export all shared types for convenient client-side imports
export type {
  AuthUser,
  ExerciseListItem,
  ColumnStat,
  ExerciseDetail,
  ExerciseColumn,
  ColumnConfig,
  DependentPicklistConfig,
  ReferenceLink,
  ValidationRule,
  ExerciseStats,
  EnrichmentRecord,
  RecordQueryParams,
  PaginatedRecords,
  CellError,
  ClassificationPayload,
  ClassificationResult,
  BulkClassificationPayload,
  BulkClassificationResult,
  AdminExerciseListItem,
  AssignedUserSummary,
  ExerciseProgressDetail,
  UserProgress,
  ApiResponse,
  ApiError,
  ApiResult,
} from '@mapforge/shared';
